// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MessageChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code proto.MessageChat}
   */
  public  static final class MessageChat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.MessageChat)
      MessageChatOrBuilder {
    // Use MessageChat.newBuilder() to construct.
    private MessageChat(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private MessageChat() {
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Message.internal_static_proto_MessageChat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Message.internal_static_proto_MessageChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Message.MessageChat.class, proto.Message.MessageChat.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static proto.Message.MessageChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Message.MessageChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Message.MessageChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Message.MessageChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Message.MessageChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Message.MessageChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.Message.MessageChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.Message.MessageChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.Message.MessageChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Message.MessageChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Message.MessageChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MessageChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MessageChat)
        proto.Message.MessageChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Message.internal_static_proto_MessageChat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Message.internal_static_proto_MessageChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Message.MessageChat.class, proto.Message.MessageChat.Builder.class);
      }

      // Construct using proto.Message.MessageChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Message.internal_static_proto_MessageChat_descriptor;
      }

      public proto.Message.MessageChat getDefaultInstanceForType() {
        return proto.Message.MessageChat.getDefaultInstance();
      }

      public proto.Message.MessageChat build() {
        proto.Message.MessageChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Message.MessageChat buildPartial() {
        proto.Message.MessageChat result = new proto.Message.MessageChat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Message.MessageChat) {
          return mergeFrom((proto.Message.MessageChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Message.MessageChat other) {
        if (other == proto.Message.MessageChat.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Message.MessageChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Message.MessageChat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.MessageChat)
    }

    // @@protoc_insertion_point(class_scope:proto.MessageChat)
    private static final proto.Message.MessageChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Message.MessageChat();
    }

    public static proto.Message.MessageChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<MessageChat> PARSER =
        new com.google.protobuf.AbstractParser<MessageChat>() {
      public MessageChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MessageChat(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageChat> getParserForType() {
      return PARSER;
    }

    public proto.Message.MessageChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MessageWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
     */
    proto.Message.MessageWrapper.MessageType getType();

    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *unique message code
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *unique message code
     * </pre>
     */
    int getCode();

    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *server time
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *server time
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>optional .proto.MessageChat chat = 4;</code>
     */
    boolean hasChat();
    /**
     * <code>optional .proto.MessageChat chat = 4;</code>
     */
    proto.Message.MessageChat getChat();
    /**
     * <code>optional .proto.MessageChat chat = 4;</code>
     */
    proto.Message.MessageChatOrBuilder getChatOrBuilder();

    /**
     * <code>optional .proto.PlayerConnection player = 5;</code>
     */
    boolean hasPlayer();
    /**
     * <code>optional .proto.PlayerConnection player = 5;</code>
     */
    proto.Player.PlayerConnection getPlayer();
    /**
     * <code>optional .proto.PlayerConnection player = 5;</code>
     */
    proto.Player.PlayerConnectionOrBuilder getPlayerOrBuilder();
  }
  /**
   * Protobuf type {@code proto.MessageWrapper}
   */
  public  static final class MessageWrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.MessageWrapper)
      MessageWrapperOrBuilder {
    // Use MessageWrapper.newBuilder() to construct.
    private MessageWrapper(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private MessageWrapper() {
      type_ = 1;
      code_ = 0;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              proto.Message.MessageWrapper.MessageType value = proto.Message.MessageWrapper.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 34: {
              proto.Message.MessageChat.Builder subBuilder = null;
              if (bodyCase_ == 4) {
                subBuilder = ((proto.Message.MessageChat) body_).toBuilder();
              }
              body_ = input.readMessage(proto.Message.MessageChat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.Message.MessageChat) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 4;
              break;
            }
            case 42: {
              proto.Player.PlayerConnection.Builder subBuilder = null;
              if (bodyCase_ == 5) {
                subBuilder = ((proto.Player.PlayerConnection) body_).toBuilder();
              }
              body_ = input.readMessage(proto.Player.PlayerConnection.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((proto.Player.PlayerConnection) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 5;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Message.internal_static_proto_MessageWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Message.internal_static_proto_MessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Message.MessageWrapper.class, proto.Message.MessageWrapper.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.MessageWrapper.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHAT = 1;</code>
       */
      CHAT(0, 1),
      /**
       * <code>PLAYER_CONNECTION = 2;</code>
       */
      PLAYER_CONNECTION(1, 2),
      ;

      /**
       * <code>CHAT = 1;</code>
       */
      public static final int CHAT_VALUE = 1;
      /**
       * <code>PLAYER_CONNECTION = 2;</code>
       */
      public static final int PLAYER_CONNECTION_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return CHAT;
          case 2: return PLAYER_CONNECTION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.Message.MessageWrapper.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.MessageWrapper.MessageType)
    }

    private int bitField0_;
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      CHAT(4),
      PLAYER(5),
      BODY_NOT_SET(0);
      private int value = 0;
      private BodyCase(int value) {
        this.value = value;
      }
      public static BodyCase valueOf(int value) {
        switch (value) {
          case 4: return CHAT;
          case 5: return PLAYER;
          case 0: return BODY_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.valueOf(
          bodyCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
     */
    public proto.Message.MessageWrapper.MessageType getType() {
      proto.Message.MessageWrapper.MessageType result = proto.Message.MessageWrapper.MessageType.valueOf(type_);
      return result == null ? proto.Message.MessageWrapper.MessageType.CHAT : result;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *unique message code
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 code = 2;</code>
     *
     * <pre>
     *unique message code
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *server time
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *server time
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CHAT_FIELD_NUMBER = 4;
    /**
     * <code>optional .proto.MessageChat chat = 4;</code>
     */
    public boolean hasChat() {
      return bodyCase_ == 4;
    }
    /**
     * <code>optional .proto.MessageChat chat = 4;</code>
     */
    public proto.Message.MessageChat getChat() {
      if (bodyCase_ == 4) {
         return (proto.Message.MessageChat) body_;
      }
      return proto.Message.MessageChat.getDefaultInstance();
    }
    /**
     * <code>optional .proto.MessageChat chat = 4;</code>
     */
    public proto.Message.MessageChatOrBuilder getChatOrBuilder() {
      if (bodyCase_ == 4) {
         return (proto.Message.MessageChat) body_;
      }
      return proto.Message.MessageChat.getDefaultInstance();
    }

    public static final int PLAYER_FIELD_NUMBER = 5;
    /**
     * <code>optional .proto.PlayerConnection player = 5;</code>
     */
    public boolean hasPlayer() {
      return bodyCase_ == 5;
    }
    /**
     * <code>optional .proto.PlayerConnection player = 5;</code>
     */
    public proto.Player.PlayerConnection getPlayer() {
      if (bodyCase_ == 5) {
         return (proto.Player.PlayerConnection) body_;
      }
      return proto.Player.PlayerConnection.getDefaultInstance();
    }
    /**
     * <code>optional .proto.PlayerConnection player = 5;</code>
     */
    public proto.Player.PlayerConnectionOrBuilder getPlayerOrBuilder() {
      if (bodyCase_ == 5) {
         return (proto.Player.PlayerConnection) body_;
      }
      return proto.Player.PlayerConnection.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasChat()) {
        if (!getChat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPlayer()) {
        if (!getPlayer().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (bodyCase_ == 4) {
        output.writeMessage(4, (proto.Message.MessageChat) body_);
      }
      if (bodyCase_ == 5) {
        output.writeMessage(5, (proto.Player.PlayerConnection) body_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (bodyCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (proto.Message.MessageChat) body_);
      }
      if (bodyCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (proto.Player.PlayerConnection) body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static proto.Message.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Message.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Message.MessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Message.MessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Message.MessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Message.MessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.Message.MessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.Message.MessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.Message.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Message.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Message.MessageWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MessageWrapper)
        proto.Message.MessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Message.internal_static_proto_MessageWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Message.internal_static_proto_MessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Message.MessageWrapper.class, proto.Message.MessageWrapper.Builder.class);
      }

      // Construct using proto.Message.MessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Message.internal_static_proto_MessageWrapper_descriptor;
      }

      public proto.Message.MessageWrapper getDefaultInstanceForType() {
        return proto.Message.MessageWrapper.getDefaultInstance();
      }

      public proto.Message.MessageWrapper build() {
        proto.Message.MessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Message.MessageWrapper buildPartial() {
        proto.Message.MessageWrapper result = new proto.Message.MessageWrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (bodyCase_ == 4) {
          if (chatBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = chatBuilder_.build();
          }
        }
        if (bodyCase_ == 5) {
          if (playerBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = playerBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Message.MessageWrapper) {
          return mergeFrom((proto.Message.MessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Message.MessageWrapper other) {
        if (other == proto.Message.MessageWrapper.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        switch (other.getBodyCase()) {
          case CHAT: {
            mergeChat(other.getChat());
            break;
          }
          case PLAYER: {
            mergePlayer(other.getPlayer());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasCode()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        if (hasChat()) {
          if (!getChat().isInitialized()) {
            return false;
          }
        }
        if (hasPlayer()) {
          if (!getPlayer().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Message.MessageWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Message.MessageWrapper) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.valueOf(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
       */
      public proto.Message.MessageWrapper.MessageType getType() {
        proto.Message.MessageWrapper.MessageType result = proto.Message.MessageWrapper.MessageType.valueOf(type_);
        return result == null ? proto.Message.MessageWrapper.MessageType.CHAT : result;
      }
      /**
       * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
       */
      public Builder setType(proto.Message.MessageWrapper.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.MessageWrapper.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *unique message code
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *unique message code
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *unique message code
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 2;</code>
       *
       * <pre>
       *unique message code
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *server time
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *server time
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *server time
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *server time
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          proto.Message.MessageChat, proto.Message.MessageChat.Builder, proto.Message.MessageChatOrBuilder> chatBuilder_;
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public boolean hasChat() {
        return bodyCase_ == 4;
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public proto.Message.MessageChat getChat() {
        if (chatBuilder_ == null) {
          if (bodyCase_ == 4) {
            return (proto.Message.MessageChat) body_;
          }
          return proto.Message.MessageChat.getDefaultInstance();
        } else {
          if (bodyCase_ == 4) {
            return chatBuilder_.getMessage();
          }
          return proto.Message.MessageChat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public Builder setChat(proto.Message.MessageChat value) {
        if (chatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          chatBuilder_.setMessage(value);
        }
        bodyCase_ = 4;
        return this;
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public Builder setChat(
          proto.Message.MessageChat.Builder builderForValue) {
        if (chatBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          chatBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 4;
        return this;
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public Builder mergeChat(proto.Message.MessageChat value) {
        if (chatBuilder_ == null) {
          if (bodyCase_ == 4 &&
              body_ != proto.Message.MessageChat.getDefaultInstance()) {
            body_ = proto.Message.MessageChat.newBuilder((proto.Message.MessageChat) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 4) {
            chatBuilder_.mergeFrom(value);
          }
          chatBuilder_.setMessage(value);
        }
        bodyCase_ = 4;
        return this;
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public Builder clearChat() {
        if (chatBuilder_ == null) {
          if (bodyCase_ == 4) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 4) {
            bodyCase_ = 0;
            body_ = null;
          }
          chatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public proto.Message.MessageChat.Builder getChatBuilder() {
        return getChatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      public proto.Message.MessageChatOrBuilder getChatOrBuilder() {
        if ((bodyCase_ == 4) && (chatBuilder_ != null)) {
          return chatBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 4) {
            return (proto.Message.MessageChat) body_;
          }
          return proto.Message.MessageChat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.MessageChat chat = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          proto.Message.MessageChat, proto.Message.MessageChat.Builder, proto.Message.MessageChatOrBuilder> 
          getChatFieldBuilder() {
        if (chatBuilder_ == null) {
          if (!(bodyCase_ == 4)) {
            body_ = proto.Message.MessageChat.getDefaultInstance();
          }
          chatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              proto.Message.MessageChat, proto.Message.MessageChat.Builder, proto.Message.MessageChatOrBuilder>(
                  (proto.Message.MessageChat) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 4;
        onChanged();;
        return chatBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          proto.Player.PlayerConnection, proto.Player.PlayerConnection.Builder, proto.Player.PlayerConnectionOrBuilder> playerBuilder_;
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public boolean hasPlayer() {
        return bodyCase_ == 5;
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public proto.Player.PlayerConnection getPlayer() {
        if (playerBuilder_ == null) {
          if (bodyCase_ == 5) {
            return (proto.Player.PlayerConnection) body_;
          }
          return proto.Player.PlayerConnection.getDefaultInstance();
        } else {
          if (bodyCase_ == 5) {
            return playerBuilder_.getMessage();
          }
          return proto.Player.PlayerConnection.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public Builder setPlayer(proto.Player.PlayerConnection value) {
        if (playerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          playerBuilder_.setMessage(value);
        }
        bodyCase_ = 5;
        return this;
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public Builder setPlayer(
          proto.Player.PlayerConnection.Builder builderForValue) {
        if (playerBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          playerBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 5;
        return this;
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public Builder mergePlayer(proto.Player.PlayerConnection value) {
        if (playerBuilder_ == null) {
          if (bodyCase_ == 5 &&
              body_ != proto.Player.PlayerConnection.getDefaultInstance()) {
            body_ = proto.Player.PlayerConnection.newBuilder((proto.Player.PlayerConnection) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 5) {
            playerBuilder_.mergeFrom(value);
          }
          playerBuilder_.setMessage(value);
        }
        bodyCase_ = 5;
        return this;
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public Builder clearPlayer() {
        if (playerBuilder_ == null) {
          if (bodyCase_ == 5) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 5) {
            bodyCase_ = 0;
            body_ = null;
          }
          playerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public proto.Player.PlayerConnection.Builder getPlayerBuilder() {
        return getPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      public proto.Player.PlayerConnectionOrBuilder getPlayerOrBuilder() {
        if ((bodyCase_ == 5) && (playerBuilder_ != null)) {
          return playerBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 5) {
            return (proto.Player.PlayerConnection) body_;
          }
          return proto.Player.PlayerConnection.getDefaultInstance();
        }
      }
      /**
       * <code>optional .proto.PlayerConnection player = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          proto.Player.PlayerConnection, proto.Player.PlayerConnection.Builder, proto.Player.PlayerConnectionOrBuilder> 
          getPlayerFieldBuilder() {
        if (playerBuilder_ == null) {
          if (!(bodyCase_ == 5)) {
            body_ = proto.Player.PlayerConnection.getDefaultInstance();
          }
          playerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              proto.Player.PlayerConnection, proto.Player.PlayerConnection.Builder, proto.Player.PlayerConnectionOrBuilder>(
                  (proto.Player.PlayerConnection) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 5;
        onChanged();;
        return playerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.MessageWrapper)
    }

    // @@protoc_insertion_point(class_scope:proto.MessageWrapper)
    private static final proto.Message.MessageWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Message.MessageWrapper();
    }

    public static proto.Message.MessageWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<MessageWrapper> PARSER =
        new com.google.protobuf.AbstractParser<MessageWrapper>() {
      public MessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MessageWrapper(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageWrapper> getParserForType() {
      return PARSER;
    }

    public proto.Message.MessageWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MessageChat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_MessageChat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MessageWrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_MessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\005proto\032\014Player.proto\"\033\n\013" +
      "MessageChat\022\014\n\004text\030\001 \002(\t\"\351\001\n\016MessageWra" +
      "pper\022/\n\004type\030\001 \002(\0162!.proto.MessageWrappe" +
      "r.MessageType\022\014\n\004code\030\002 \002(\005\022\021\n\ttimestamp" +
      "\030\003 \002(\003\022\"\n\004chat\030\004 \001(\0132\022.proto.MessageChat" +
      "H\000\022)\n\006player\030\005 \001(\0132\027.proto.PlayerConnect" +
      "ionH\000\".\n\013MessageType\022\010\n\004CHAT\020\001\022\025\n\021PLAYER" +
      "_CONNECTION\020\002B\006\n\004bodyB\020\n\005protoB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.Player.getDescriptor(),
        }, assigner);
    internal_static_proto_MessageChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MessageChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_MessageChat_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_proto_MessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_MessageWrapper_descriptor,
        new java.lang.String[] { "Type", "Code", "Timestamp", "Chat", "Player", "Body", });
    proto.Player.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
